const autoCaptcha = document.getElementById("AutoGeneratedValue");
const userCaptcha = document.getElementById("userCaptchaValue");
const message = document.getElementById("message");
const checkIcon = document.getElementById("checkIcon");


let CAPTCHAText = "";   //Global Variabld

generateAutoCaptcha();
//Function to generate Captcha
function generateAutoCaptcha() {
  let Length = 6;
  let Captchas = [];
  const randomChar = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"; //Captcha should be in this characher 

  for(let i=0; i <  Length; i++) {
    let index = Math.floor(Math.random() * randomChar.length);   //This gives a random value using character
    Captchas.push(randomChar[index]);
  }
  autoCaptcha.innerHTML = Captchas.join(" ")     //Join the random generated value
  CAPTCHAText = Captchas.join("");  //This is used to enter the generated value in input.
  message.innerText = "";
  userCaptcha.value = "";
}

//Function for user to enter the generated captcha
function DoValidateCaptchas() {
  console.log(CAPTCHAText, userCaptcha.value);

  if(userCaptcha.value === CAPTCHAText) {
    message.innerText = "Valid Captcha";
    message.setAttribute("class", "green");
    checkIcon.classList.remove("fa-xmark");
    checkIcon.classList.add("fa-check");
    checkIcon.style.color = "green";
  }else {
    message.innerText = "In-Valid Captcha, Try Again";
    message.setAttribute("class", "red");
    checkIcon.classList.remove("fa-check");
    checkIcon.classList.add("fa-xmark");
    checkIcon.style.color = "red"; 
  }
}